--customer_orders cleaning
SELECT * FROM DBO.CUSTOMER_ORDERS;

UPDATE DBO.CUSTOMER_ORDERS
SET EXCLUSIONS = NULL
WHERE (EXCLUSIONS ='' OR EXCLUSIONS ='null');

UPDATE DBO.CUSTOMER_ORDERS
SET EXTRAS=NULL
WHERE (EXTRAS='' OR EXTRAS='null');

--runner_orders
SELECT * FROM DBO.runner_orders;

update dbo.runner_orders
set pickup_time=NULL
WHERE PICKUP_TIME='null';

UPDATE DBO.RUNNER_ORDERS
SET DISTANCE= CASE 
WHEN DISTANCE='null' THEN NULL
ELSE CAST(REPLACE(DISTANCE, 'km', '') AS FLOAT)
END;

UPDATE DBO.RUNNER_ORDERS
SET DURATION = CASE
WHEN DURATION='null' THEN NULL
WHEN SUBSTRING(DURATION, 3, LEN(DURATION))='minutes' THEN CAST(REPLACE(DURATION, 'minutes', '') AS INTEGER)
WHEN SUBSTRING(DURATION, 3, LEN(DURATION))=' minutes' THEN CAST(REPLACE(DURATION, ' minutes', '') AS INTEGER)
WHEN SUBSTRING(DURATION, 3, LEN(DURATION))='minute' THEN CAST(REPLACE(DURATION, 'minute', '') AS INTEGER)
WHEN SUBSTRING(DURATION, 3, LEN(DURATION))=' minute' THEN CAST(REPLACE(DURATION, ' minute', '') AS INTEGER)
WHEN SUBSTRING(DURATION, 3, LEN(DURATION))=' mins' THEN CAST(REPLACE(DURATION, ' mins', '') AS INTEGER)
ELSE CAST(REPLACE(DURATION, 'mins', '') AS INTEGER)
END;

update dbo.runner_orders
set cancellation=NULL
WHERE CANCELLATION='' OR CANCELLATION='null';
